
const getStock = ()=>{
    return new Promise((resolve)=>{

        setTimeout(()=>{
            resolve([
                {id: 1, title: "Licor 1", category: 'licores', img: '/img/licor.webp', stock: 20, precio: 2500, detail: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras pellentesque vitae libero in euismod. Ut eget mollis est. Donec ut leo id nisi sollicitudin convallis. Proin aliquam purus nulla, at consequat libero mattis nec. Sed nec ligula et ipsum sollicitudin commodo. Quisque ullamcorper tortor tortor, nec condimentum nulla lacinia id.'},
                {id: 2, title: "Licor 2", category: 'licores', img: '/img/licor.webp', stock: 15, precio: 3500, detail: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras pellentesque vitae libero in euismod. Ut eget mollis est. Donec ut leo id nisi sollicitudin convallis. Proin aliquam purus nulla, at consequat libero mattis nec. Sed nec ligula et ipsum sollicitudin commodo. Quisque ullamcorper tortor tortor, nec condimentum nulla lacinia id.'},
                {id: 3, title: "Licor 3", category: 'licores', img: '/img/licor.webp', stock: 12, precio: 4000, detail: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras pellentesque vitae libero in euismod. Ut eget mollis est. Donec ut leo id nisi sollicitudin convallis. Proin aliquam purus nulla, at consequat libero mattis nec. Sed nec ligula et ipsum sollicitudin commodo. Quisque ullamcorper tortor tortor, nec condimentum nulla lacinia id.'},
                {id: 4, title: "Licor 4", category: 'licores', img: '/img/licor.webp', stock: 10, precio: 8000, detail: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras pellentesque vitae libero in euismod. Ut eget mollis est. Donec ut leo id nisi sollicitudin convallis. Proin aliquam purus nulla, at consequat libero mattis nec. Sed nec ligula et ipsum sollicitudin commodo. Quisque ullamcorper tortor tortor, nec condimentum nulla lacinia id.'},
                {id: 5, title: "Licor 5", category: 'licores', img: '/img/licor.webp', stock: 8, precio: 11000, detail: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras pellentesque vitae libero in euismod. Ut eget mollis est. Donec ut leo id nisi sollicitudin convallis. Proin aliquam purus nulla, at consequat libero mattis nec. Sed nec ligula et ipsum sollicitudin commodo. Quisque ullamcorper tortor tortor, nec condimentum nulla lacinia id.'},
                {id: 6, title: "Licor 6", category: 'licores', img: '/img/licor.webp', stock: 4, precio: 15000, detail: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras pellentesque vitae libero in euismod. Ut eget mollis est. Donec ut leo id nisi sollicitudin convallis. Proin aliquam purus nulla, at consequat libero mattis nec. Sed nec ligula et ipsum sollicitudin commodo. Quisque ullamcorper tortor tortor, nec condimentum nulla lacinia id.'},
                {id: 7, title: "Vino 1", category: 'vinos', img: '/img/vino.webp', stock: 20, precio: 2500, detail: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras pellentesque vitae libero in euismod. Ut eget mollis est. Donec ut leo id nisi sollicitudin convallis. Proin aliquam purus nulla, at consequat libero mattis nec. Sed nec ligula et ipsum sollicitudin commodo. Quisque ullamcorper tortor tortor, nec condimentum nulla lacinia id.'},
                {id: 8, title: "Vino 2", category: 'vinos', img: '/img/vino.webp', stock: 15, precio: 3500, detail: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras pellentesque vitae libero in euismod. Ut eget mollis est. Donec ut leo id nisi sollicitudin convallis. Proin aliquam purus nulla, at consequat libero mattis nec. Sed nec ligula et ipsum sollicitudin commodo. Quisque ullamcorper tortor tortor, nec condimentum nulla lacinia id.'},
                {id: 9, title: "Vino 3", category: 'vinos', img: '/img/vino.webp', stock: 12, precio: 4000, detail: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras pellentesque vitae libero in euismod. Ut eget mollis est. Donec ut leo id nisi sollicitudin convallis. Proin aliquam purus nulla, at consequat libero mattis nec. Sed nec ligula et ipsum sollicitudin commodo. Quisque ullamcorper tortor tortor, nec condimentum nulla lacinia id.'},
                {id: 10, title: "Vino 4", category: 'vinos', img: '/img/vino.webp', stock: 10, precio: 8000, detail: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras pellentesque vitae libero in euismod. Ut eget mollis est. Donec ut leo id nisi sollicitudin convallis. Proin aliquam purus nulla, at consequat libero mattis nec. Sed nec ligula et ipsum sollicitudin commodo. Quisque ullamcorper tortor tortor, nec condimentum nulla lacinia id.'},
                {id: 11, title: "Vino 5", category: 'vinos', img: '/img/vino.webp', stock: 8, precio: 11000, detail: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras pellentesque vitae libero in euismod. Ut eget mollis est. Donec ut leo id nisi sollicitudin convallis. Proin aliquam purus nulla, at consequat libero mattis nec. Sed nec ligula et ipsum sollicitudin commodo. Quisque ullamcorper tortor tortor, nec condimentum nulla lacinia id.'},
                {id: 12, title: "Vino 6", category: 'vinos', img: '/img/vino.webp', stock: 4, precio: 15000, detail: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras pellentesque vitae libero in euismod. Ut eget mollis est. Donec ut leo id nisi sollicitudin convallis. Proin aliquam purus nulla, at consequat libero mattis nec. Sed nec ligula et ipsum sollicitudin commodo. Quisque ullamcorper tortor tortor, nec condimentum nulla lacinia id.'},
                {id: 13, title: "Cerveza 1", category: 'cervezas', img: '/img/cervezas.webp', stock: 20, precio: 2500, detail: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras pellentesque vitae libero in euismod. Ut eget mollis est. Donec ut leo id nisi sollicitudin convallis. Proin aliquam purus nulla, at consequat libero mattis nec. Sed nec ligula et ipsum sollicitudin commodo. Quisque ullamcorper tortor tortor, nec condimentum nulla lacinia id.'},
                {id: 14, title: "Cerveza 2", category: 'cervezas', img: '/img/cervezas.webp', stock: 15, precio: 3500, detail: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras pellentesque vitae libero in euismod. Ut eget mollis est. Donec ut leo id nisi sollicitudin convallis. Proin aliquam purus nulla, at consequat libero mattis nec. Sed nec ligula et ipsum sollicitudin commodo. Quisque ullamcorper tortor tortor, nec condimentum nulla lacinia id.'},
                {id: 15, title: "Cerveza 3", category: 'cervezas', img: '/img/cervezas.webp', stock: 12, precio: 4000, detail: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras pellentesque vitae libero in euismod. Ut eget mollis est. Donec ut leo id nisi sollicitudin convallis. Proin aliquam purus nulla, at consequat libero mattis nec. Sed nec ligula et ipsum sollicitudin commodo. Quisque ullamcorper tortor tortor, nec condimentum nulla lacinia id.'},
                {id: 16, title: "Cerveza 4", category: 'cervezas', img: '/img/cervezas.webp', stock: 10, precio: 8000, detail: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras pellentesque vitae libero in euismod. Ut eget mollis est. Donec ut leo id nisi sollicitudin convallis. Proin aliquam purus nulla, at consequat libero mattis nec. Sed nec ligula et ipsum sollicitudin commodo. Quisque ullamcorper tortor tortor, nec condimentum nulla lacinia id.'},
                {id: 17, title: "Cerveza 5", category: 'cervezas', img: '/img/cervezas.webp', stock: 8, precio: 11000, detail: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras pellentesque vitae libero in euismod. Ut eget mollis est. Donec ut leo id nisi sollicitudin convallis. Proin aliquam purus nulla, at consequat libero mattis nec. Sed nec ligula et ipsum sollicitudin commodo. Quisque ullamcorper tortor tortor, nec condimentum nulla lacinia id.'},
                {id: 18, title: "Cerveza 6", category: 'cervezas', img: '/img/cervezas.webp', stock: 4, precio: 15000, detail: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras pellentesque vitae libero in euismod. Ut eget mollis est. Donec ut leo id nisi sollicitudin convallis. Proin aliquam purus nulla, at consequat libero mattis nec. Sed nec ligula et ipsum sollicitudin commodo. Quisque ullamcorper tortor tortor, nec condimentum nulla lacinia id.'},
                {id: 19, title: "Whisky 1", category: 'whiskys', img: '/img/whisky.jpg', stock: 20, precio: 2500, detail: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras pellentesque vitae libero in euismod. Ut eget mollis est. Donec ut leo id nisi sollicitudin convallis. Proin aliquam purus nulla, at consequat libero mattis nec. Sed nec ligula et ipsum sollicitudin commodo. Quisque ullamcorper tortor tortor, nec condimentum nulla lacinia id.'},
                {id: 20, title: "Whisky 2", category: 'whiskys', img: '/img/whisky.jpg', stock: 15, precio: 3500, detail: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras pellentesque vitae libero in euismod. Ut eget mollis est. Donec ut leo id nisi sollicitudin convallis. Proin aliquam purus nulla, at consequat libero mattis nec. Sed nec ligula et ipsum sollicitudin commodo. Quisque ullamcorper tortor tortor, nec condimentum nulla lacinia id.'},
                {id: 21, title: "Whisky 3", category: 'whiskys', img: '/img/whisky.jpg', stock: 12, precio: 4000, detail: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras pellentesque vitae libero in euismod. Ut eget mollis est. Donec ut leo id nisi sollicitudin convallis. Proin aliquam purus nulla, at consequat libero mattis nec. Sed nec ligula et ipsum sollicitudin commodo. Quisque ullamcorper tortor tortor, nec condimentum nulla lacinia id.'},
                {id: 22, title: "Whisky 4", category: 'whiskys', img: '/img/whisky.jpg', stock: 10, precio: 8000, detail: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras pellentesque vitae libero in euismod. Ut eget mollis est. Donec ut leo id nisi sollicitudin convallis. Proin aliquam purus nulla, at consequat libero mattis nec. Sed nec ligula et ipsum sollicitudin commodo. Quisque ullamcorper tortor tortor, nec condimentum nulla lacinia id.'},
                {id: 23, title: "Whisky 5", category: 'whiskys', img: '/img/whisky.jpg', stock: 8, precio: 11000, detail: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras pellentesque vitae libero in euismod. Ut eget mollis est. Donec ut leo id nisi sollicitudin convallis. Proin aliquam purus nulla, at consequat libero mattis nec. Sed nec ligula et ipsum sollicitudin commodo. Quisque ullamcorper tortor tortor, nec condimentum nulla lacinia id.'},
                {id: 24, title: "Whisky 6", category: 'whiskys', img: '/img/whisky.jpg', stock: 4, precio: 15000, detail: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras pellentesque vitae libero in euismod. Ut eget mollis est. Donec ut leo id nisi sollicitudin convallis. Proin aliquam purus nulla, at consequat libero mattis nec. Sed nec ligula et ipsum sollicitudin commodo. Quisque ullamcorper tortor tortor, nec condimentum nulla lacinia id.'}
            ])

        }, 1000)
    })
}

export default getStock;